version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_charkota
      - POSTGRES_USER=usr_charkota
      - POSTGRES_PASSWORD=pass1234
